version: '3.8'

services:
  web:
    build: .
    container_name: django_zeiss_gpt
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - db_data:/app/db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  db_data: