# Generated by Django 5.1.2 on 2024-11-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_chatmessage_regenerated_alter_chatsession_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[("user", "User"), ("ai", "AI")], max_length=10
            ),
        ),
    ]
